upgrade circle

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,263 +1,204 @@
-aliases:
-  - &serverless_build_test_deploy
-    docker:
-      # - image: circleci/node:8.10
-      # - image: circleci/python:3.8.1
-      - image: nikolaik/python-nodejs
-    steps:
-      - checkout:
-          path: ~/clicker
-      - restore_cache:
-          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
-      - run:
-          name: Install dependencies
-          command: npm i
-      - save_cache:
-          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
-          paths:
-            - ./node_modules
-      - run:
-          name: Run tests
-          command: npm test
-      - run:
-          name: Deploy serverless function
-          branches:
-            only:
-              - master
-              - release
-              - develop
-          command: |
-            npm run build --if-present
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              npx serverless deploy --stage prod --verbose
-            fi
-            if [ "${CIRCLE_BRANCH}" == "release" ]; then
-              npx serverless deploy --stage release --verbose
-            fi
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              npx serverless deploy --stage develop --verbose
-            fi
 version: 2.1
-jobs:
-  build:
+
+parameters:
+  # By default we enable the main workflow
+  trigger:
+    type: boolean
+    default: true
+
+  # Add a boolean parameter on each package.
+  core:
+    type: boolean
+    default: false
+  components:
+    type: boolean
+    default: false
+
+executors:
+  node:
     docker:
-      - image: circleci/node:8.10
-    branches:
-      only:
-        - master
-        - release
-        - develop
+      - image: circleci/node
+
+jobs:
+  trigger-workflows:
+    executor: node
     steps:
       - checkout
+      - run: yarn --frozen-lockfile
       - run:
-          name: Determine which projects have changed and trigger the builds
-          command: |
-            # Identify modified directories
-            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
-            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
-            #first commit in a branch
-            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
-              COMMITS="origin/master"
-            else
-              COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
-            fi
-            git diff --name-only $COMMITS | cut -d/ -f-2 | sort -u > projects
-            echo -e "Modified directories:\n`cat projects`\n"
-            # If modified directories contain Gopkg/vendor directores, build all projects and exit
-            buildall=0
-            for project in `cat projects`; do
-              if [[ ${project} =~ "Gopkg" || ${project} =~ "vendor" ]]; then
-                buildall=1
-                echo -e "Dependencies change detected. building all $CIRCLE_PROJECT_REPONAME"
-                curl -s -u ${CIRCLE_TOKEN}: \
-                    -d build_parameters[CIRCLE_JOB]=all \
-                    https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
-              fi
-              if [[ ${buildall} -eq 1 ]]; then
-                exit 0
-              fi
-            done
-            # Build affected projects and their dependencies
-            projects_inc_dep=(`cat projects`)
-            echo -e "Calculating dependencies\n"
-            for dir in `ls -d */`; do
-              for dep in `go list -f '{{ .Deps }}' ./${dir} 2>/dev/null`; do
-                for project_dep in `echo $dep | grep github.com/tufin/$CIRCLE_PROJECT_REPONAME | egrep -v "vendor|${dir%\/}"`; do
-                  if [[ " ${projects_inc_dep[@]} " =~ " ${project_dep##*\/} " ]] && ! [[ " ${projects_inc_dep[@]} " =~ " ${dir%\/} " ]]; then
-                    projects_inc_dep+=(${dir%\/})
-                  fi
-                done
-              done
-            done
-            echo -e "Building: ${projects_inc_dep[@]}\n"
-            for project in ${projects_inc_dep[@]}; do
-              if grep -Fxq $project .projects; then
-                printf "\nTriggerring build for project: "$project, ${CIRCLE_TOKEN}, ${project}, https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
-                curl -s -u ${CIRCLE_TOKEN}: \
-                  -d build_parameters[CIRCLE_JOB]=${project} \
-                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH
-              fi
-            done
+          name: Trigger workflows
+          command: node ./circleci.js
+
+  new_version:
+    executor: node
+    steps:
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "7d:4f:a9:ac:9d:54:47:bc:4d:aa:bd:b0:98:20:df:91"
+      - run: git config user.email "ci@julienkarst.com" && git config user.name "[CI] 🤖"
+      - run: yarn bump:version
+
+  lint:
+    parameters:
+      package_name:
+        type: string
+    executor: node
+    steps:
+      - run:
+          name: Running linter on << parameters.package_name >>
+          command: echo << parameters.package_name >> lint
+
+  test:
+    parameters:
+      package_name:
+        type: string
+    executor: node
+    steps:
+      - run:
+          name: Running linter on << parameters.package_name >>
+          command: echo << parameters.package_name >> lint
+
 workflows:
-  functions/admin:
-    working_directory: ~/clicker/functions/admin
-    <<: *serverless_build_test_deploy
-  functions/analytics:
-    working_directory: ~/clicker/functions/analytics
-    <<: *serverless_build_test_deploy
-  functions/app:
-    working_directory: ~/clicker/functions/app
-    <<: *serverless_build_test_deploy
-  functions/game:
-    working_directory: ~/clicker/functions/game
-    <<: *serverless_build_test_deploy
-  functions/job:
-    working_directory: ~/clicker/functions/job
-    <<: *serverless_build_test_deploy
-  functions/lead:
-    working_directory: ~/clicker/functions/lead
-    <<: *serverless_build_test_deploy
-  functions/location:
-    working_directory: ~/clicker/functions/location
-    <<: *serverless_build_test_deploy
-  functions/notification:
-    working_directory: ~/clicker/functions/notification
-    <<: *serverless_build_test_deploy
-  functions/program:
-    working_directory: ~/clicker/functions/program
-    <<: *serverless_build_test_deploy
-  functions/receiver:
-    working_directory: ~/clicker/functions/receiver
-    <<: *serverless_build_test_deploy
-  functions/remote:
-    working_directory: ~/clicker/functions/remote
-    <<: *serverless_build_test_deploy
-  functions/reservation:
-    working_directory: ~/clicker/functions/reservation
-    <<: *serverless_build_test_deploy
-  functions/user:
-    working_directory: ~/clicker/functions/user
-    <<: *serverless_build_test_deploy
-  functions/widget:
-    working_directory: ~/clicker/functions/widget
-    <<: *serverless_build_test_deploy
-  web/app:
-    working_directory: ~/clicker/web/app
-    docker:
-      - image: circleci/node:8.10
+  version: 2
+
+  # The main workflow will trigger other workflow based on file changes
+  trigger:
+    when: << pipeline.parameters.trigger >>
+    jobs:
+      - trigger-workflows
+
+jobs:
+  trigger-workflows:
+    executor: node
     steps:
+      - checkout
+      # - run: yarn --frozen-lockfile
       - run:
-          name: Trigger Netlify build + deploy
-          branches:
-            only:
-              - master
-              - release
-              - develop
+          name: Trigger workflows
           command: |
-            echo -e "deploy clicker web"
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c7458709c6a819dd611ee82
+            set -e
+
+            ## source of this code: https://github.com/labs42io/circleci-monorepo/blob/master/.circleci/circle_trigger.sh
+
+            # The root directory of packages.
+            # Use `.` if your packages are located in root.
+            ROOT="." 
+            REPOSITORY_TYPE="github"
+            CIRCLE_API="https://circleci.com/api"
+            DEFAULT_BRANCH='master'
+
+            ############################################
+            ## 0. Check for layer 8 errors
+            ############################################
+            sudo apt install jq -y
+
+            if  [[ ${CIRCLE_TOKEN} == "" ]]; then
+              SCRIPT=`realpath $0`
+              echo "You need to set CIRCLE_TOKEN as ENV-var, or this script (${SCRIPT}) will fail!"
+              exit 1
             fi
-            if [ "${CIRCLE_BRANCH}" == "release" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c74588dce2aff6b7eb9d135
+
+            ############################################
+            ## 1. Commit SHA of last CI build
+            ############################################
+            LAST_COMPLETED_BUILD_URL="${CIRCLE_API}/v1.1/project/${REPOSITORY_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}?filter=completed&limit=100&shallow=true"
+            LAST_COMPLETED_BUILD_SHA=`curl -Ss -u "${CIRCLE_TOKEN}:" "${LAST_COMPLETED_BUILD_URL}" | jq -r 'map(select(.status == "success") | select(.workflows.workflow_name != "ci")) | .[0]["vcs_revision"]'`
+
+            if  [[ ${LAST_COMPLETED_BUILD_SHA} == "null" ]]; then
+              echo -e "\e[93mThere are no completed CI builds in branch ${CIRCLE_BRANCH}.\e[0m"
+
+              # Adapted from https://gist.github.com/joechrysler/6073741
+              TREE=$(git show-branch -a \
+                | grep '\*' \
+                | grep -v `git rev-parse --abbrev-ref HEAD` \
+                | sed 's/.*\[\(.*\)\].*/\1/' \
+                | sed 's/[\^~].*//' \
+                | uniq)
+
+              REMOTE_BRANCHES=$(git branch -r | sed 's/\s*origin\///' | tr '\n' ' ')
+              PARENT_BRANCH=${DEFAULT_BRANCH}
+              for BRANCH in ${TREE[@]}
+              do
+                BRANCH=${BRANCH#"origin/"}
+                if [[ " ${REMOTE_BRANCHES[@]} " == *" ${BRANCH} "* ]]; then
+                  echo "Found the parent branch: ${CIRCLE_BRANCH}..${BRANCH}"
+                  PARENT_BRANCH=$BRANCH
+                  break
+                fi
+              done
+
+              echo "Searching for CI builds in branch '${PARENT_BRANCH}' ..."
+
+              LAST_COMPLETED_BUILD_URL="${CIRCLE_API}/v1.1/project/${REPOSITORY_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${PARENT_BRANCH}?filter=completed&limit=100&shallow=true"
+              LAST_COMPLETED_BUILD_SHA=`curl -Ss -u "${CIRCLE_TOKEN}:" "${LAST_COMPLETED_BUILD_URL}" \
+                | jq -r "map(\
+                  select(.status == \"success\") | select(.workflows.workflow_name != \"ci\") | select(.build_num < ${CIRCLE_BUILD_NUM})) \
+                | .[0][\"vcs_revision\"]"`
             fi
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c745884ad8fd5e199de18cf
+
+            if [[ ${LAST_COMPLETED_BUILD_SHA} == "null" ]]; then
+              echo -e "\e[93mNo CI builds for branch ${PARENT_BRANCH}. Using ${DEFAULT_BRANCH}.\e[0m"
+              LAST_COMPLETED_BUILD_SHA=${DEFAULT_BRANCH}
             fi
-  mobile/app:
-    working_directory: ~/clicker/mobile/app
-    docker:
-      - image: circleci/node:8.10
-    steps:
-      - run:
-          name: Trigger Netlify build + deploy
-          branches:
-            only:
-              - master
-              - release
-              - develop
-          command: |
-            echo -e "deploy clicker mobile"
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a22aad21db652db51e1
+
+            ############################################
+            ## 2. Changed packages
+            ############################################
+            PACKAGES=$(ls ${ROOT} -l | grep ^d | awk '{print $9}')
+            echo "Searching for changes since commit [${LAST_COMPLETED_BUILD_SHA:0:7}] ..."
+
+            if [[ $LAST_COMPLETED_BUILD_SHA == $DEFAULT_BRANCH ]]; then
+              FORCE_ALL_PACKS=true
             fi
-            if [ "${CIRCLE_BRANCH}" == "release" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a2933754a346bf8ef90
+
+            ## The CircleCI API parameters object
+            PARAMETERS='"trigger":false'
+            COUNT=0
+            for PACKAGE in ${PACKAGES[@]}
+            do
+              PACKAGE_PATH=${ROOT}/$PACKAGE
+              LATEST_COMMIT_SINCE_LAST_BUILD=$(git log -1 $CIRCLE_SHA1 ^$LAST_COMPLETED_BUILD_SHA --format=format:%H --full-diff ${PACKAGE_PATH#/})
+
+              if [ -n "$LATEST_COMMIT_SINCE_LAST_BUILD" ] || [ -n "$FORCE_ALL_PACKS" ]; then
+                PARAMETERS+=", \"$PACKAGE\":true"
+                
+                if [[ -n $FORCE_ALL_PACKS ]]; then
+                  echo -e "\e[36m  [+] ${PACKAGE} \e[21m will be triggered because we are on the default branch: ${DEFAULT_BRANCH} \e[0m"
+                else
+                  COUNT=$((COUNT + 1))
+                  echo -e "\e[36m  [+] ${PACKAGE} \e[21m (changed in [${LATEST_COMMIT_SINCE_LAST_BUILD:0:7}])\e[0m"
+                fi
+              else
+                echo -e "\e[90m  [-] ${PACKAGE} \e[0m"
+              fi
+
+            done
+
+            if [[ $COUNT -eq 0 ]]; then
+              echo -e "\e[93mNo changes detected in packages. Skip triggering workflows.\e[0m"
+              exit 0
             fi
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a2f1056ec16dab4338b
+
+            echo "Changes detected in ${COUNT} package(s)."
+
+            ############################################
+            ## 3. CicleCI REST API call
+            ############################################
+            DATA="{ \"branch\": \"$CIRCLE_BRANCH\", \"parameters\": { $PARAMETERS } }"
+            echo "Triggering pipeline with data:"
+            echo -e "  $DATA"
+
+            URL="${CIRCLE_API}/v2/project/${REPOSITORY_TYPE}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline"
+            HTTP_RESPONSE=$(curl -s -u ${CIRCLE_TOKEN}: -o response.txt -w "%{http_code}" -X POST --header "Content-Type: application/json" -d "$DATA" $URL)
+
+            if [ "$HTTP_RESPONSE" -ge "200" ] && [ "$HTTP_RESPONSE" -lt "300" ]; then
+              echo "API call succeeded."
+              echo "Response:"
+              cat response.txt
+            else
+              echo -e "\e[93mReceived status code: ${HTTP_RESPONSE}\e[0m"
+              echo "Response:"
+              cat response.txt
+              exit 1
             fi
-  packages/antenna:
-    working_directory: ~/clicker/packages/antenna
-    docker:
-      - image: chybie/node-aws-cli
-    steps:
-      - checkout:
-          path: ~/clicker
-      - run:
-          name: Install dependencies
-          command: npm i
-      - run:
-          name: Upload app zip to s3
-          branches:
-            only:
-              - master
-              - release
-              - develop
-          command: |
-            echo -e "upload antenna package to s3"
-            filename=
-            if [ "${CIRCLE_BRANCH}" == "master" ]; then
-              filename="antenna.tar.gz"
-            fi
-            if [ "${CIRCLE_BRANCH}" == "release" ]; then
-              filename="antenna-release.tar.gz"
-            fi
-            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
-              filename="antenna-develop.tar.gz"
-            fi
-            tar zcvf $filename *
-            aws s3 cp $filename s3://clicker-antenna/app/
-  e2e/app:
-    working_directory: ~/clicker/e2e/app
-    docker:
-      - image: cypress/base:10
-    steps:
-      - checkout:
-          path: ~/clicker
-      # - restore_cache:
-      #     key: dependency-cache-{{ checksum "package.json" }}
-      # - restore_cache:
-      #     key: cypress
-      - restore_cache:
-          keys:
-            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
-            # - v1-deps-{{ .Branch }}
-            # - v1-deps
-      - run:
-          name: Install dependencies
-          command: npm ci
-      - save_cache:
-          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
-          # cache NPM modules and the folder with the Cypress binary
-          paths:
-            - ~/.cache
-            - ./node_modules
-      # - save_cache:
-      #     key: dependency-cache-{{ checksum "package.json" }}
-      #     paths:
-      #       - ./node_modules
-      # - save_cache:
-      #     key: cypress
-      #     paths:
-      #       - /root/.cache/Cypress/3.4.1/Cypress
-      - run:
-          name: Run e2e tests
-          no_output_timeout: 3m
-          branches:
-            only:
-              - master
-              - release
-              - develop
-          command: |
-            npm run test:ci
